#!/usr/bin/env bash
# Builds the `production` branch: a snapshot of main holding only what the
# server needs at runtime (services/api/{src,public,site}, a runtime-only
# package.json and its lock). No docs, design, tests, scripts, contracts or
# Shopify extension.
#
# Each run adds one commit to `production` whose tree is the filtered tree of
# the source commit; the message names that commit. Main is never merged into
# production, so there are no modify/delete conflicts. It does not push.
#
#   scripts/build-production-branch.sh [source-ref]   # default origin/main
#   git push origin production
set -euo pipefail

SRC="${1:-origin/main}"
BRANCH=production
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

if [ -x "$ROOT/.toolchain/node-v22.17.0-darwin-arm64/bin/node" ] && "$ROOT/.toolchain/node-v22.17.0-darwin-arm64/bin/node" -v >/dev/null 2>&1; then
  export PATH="$ROOT/.toolchain/node-v22.17.0-darwin-arm64/bin:$PATH"
fi

git fetch -q origin
src_sha="$(git rev-parse "$SRC^{commit}")"
short="${src_sha:0:7}"

work="$(mktemp -d)"
trap 'git -C "$ROOT" worktree remove --force "$work" >/dev/null 2>&1 || rm -rf "$work"' EXIT
git worktree add -q --detach "$work" "$src_sha"
cd "$work"

# chain.ts loads contract ABIs from the hardhat build output at import time.
# Compile here and keep only {contractName, abi}, so production carries
# neither Solidity nor hardhat.
[ -d "$ROOT/node_modules/hardhat" ] || { echo "run npm ci in $ROOT first (hardhat compiles the ABIs)" >&2; exit 1; }
ln -s "$ROOT/node_modules" node_modules
npx hardhat compile >/dev/null
abis="$(mktemp -d)"
for sol in contracts/src/*.sol; do
  name="$(basename "$sol" .sol)"
  mkdir -p "$abis/$name.sol"
  node -e 'const a=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"));process.stdout.write(JSON.stringify({contractName:a.contractName,abi:a.abi})+"\n")' \
    "contracts/artifacts/contracts/src/$name.sol/$name.json" > "$abis/$name.sol/$name.json"
done
rm node_modules

# The allowlist. Anything not matched here is not in production.
KEEP='^(services/api/(src|public|site)/|package\.json$|package-lock\.json$|tsconfig\.json$|\.env\.example$|\.gitignore$|LICENSE$|SECURITY\.md$)'
git ls-files -z | grep -zvE "$KEEP" | xargs -0 git rm -q --
rm -rf contracts
mkdir -p contracts/artifacts/contracts
mv "$abis" contracts/artifacts/contracts/src
git add -f contracts/artifacts

# Runtime-only package.json: tsx runs the server, so it moves to
# dependencies; hardhat, typescript and the type packages go.
node - <<'EOF'
const fs = require("fs");
const p = JSON.parse(fs.readFileSync("package.json", "utf8"));
const tsx = p.devDependencies?.tsx;
if (!tsx) throw new Error("package.json has no tsx devDependency");
const out = {
  name: p.name,
  license: p.license,
  version: p.version,
  private: true,
  description: p.description,
  type: p.type,
  scripts: { start: "tsx services/api/src/server.ts" },
  dependencies: { ...p.dependencies, tsx },
};
if (p.overrides) out.overrides = p.overrides;
if (p.optionalDependencies) out.optionalDependencies = p.optionalDependencies;
fs.writeFileSync("package.json", JSON.stringify(out, null, 2) + "\n");

const t = JSON.parse(fs.readFileSync("tsconfig.json", "utf8"));
t.include = ["services/api/src/**/*.ts"];
fs.writeFileSync("tsconfig.json", JSON.stringify(t, null, 2) + "\n");
EOF
npm install --package-lock-only --no-audit --no-fund --ignore-scripts >/dev/null

cat > README.md <<EOF
# Zold — production

Generated by \`scripts/build-production-branch.sh\` on main; do not edit this
branch by hand. Source: main@${short}.

This is the code the server runs and nothing else. Development, tests, docs
and contracts live on \`main\`.

\`\`\`bash
npm ci --omit=dev
npm start
\`\`\`

Configuration is by environment variable; \`.env.example\` lists them.
EOF

git add -A
tree="$(git write-tree)"
parent="$(git -C "$ROOT" rev-parse -q --verify "refs/heads/$BRANCH" || git -C "$ROOT" rev-parse -q --verify "refs/remotes/origin/$BRANCH" || true)"

if [ -n "$parent" ] && [ "$(git rev-parse "$parent^{tree}")" = "$tree" ]; then
  echo "$BRANCH already matches main@$short; nothing to do."
  exit 0
fi

commit="$(git commit-tree "$tree" ${parent:+-p "$parent"} -m "Production snapshot of main@$short" -m "Source: $src_sha")"
git -C "$ROOT" branch -f "$BRANCH" "$commit"
echo "$BRANCH -> ${commit:0:7} (main@$short). Push with: git push origin $BRANCH"
